### ISSUE TITLE
read part 3 and make homework

### ISSUE THREAD

**Issue by KonstantinKlepikov** [KonstantinKlepikov/example-repo#12]
in this case make python file with code examples. Run that file and check - is correct executed

part 3 - pages 67-81

**Comment by RitoAgent** [comment]
Можно перенести до 27го числа?

**Comment by KonstantinKlepikov** [comment]
@RitoAgent 5 дней на то чтобы одну главу прочитать? Ничего себе у тебя темп. С таким темпом к годам 60 может и научишься чему...

**Comment by RitoAgent** [comment]
Я создал отдельно example2.py Я понял, что нужно примеры пропускать через файл "py".

**Comment by RitoAgent** [comment]
В-общем я пример разобрал по отдельности. А как мне запустить весь python файл целиком чтобы не писать по каждому примеру в комментариях в readme?

**Comment by RitoAgent** [comment]
утром перенесу в удаленный github

**Comment by RitoAgent** [comment]
Там еще упражнения оказывается есть в конце главы. Их тоже нужно разобрать перед тем как переносить

**Comment by RitoAgent** [comment]
У меня ошибку выдает SyntaxError: invalid syntax
>>> /bin/python3 /home/miha/Documents/Projects/example-repo/src/example2.py
  File "<stdin>", line 1
    /bin/python3 /home/miha/Documents/Projects/example-repo/src/example2.py
    ^
Я запускаю через треугольник "Run Python File".

**Comment by RitoAgent** [comment]
Всё я понял почему не запускается run python file. Интерпретатор надо было выключить

**Comment by KonstantinKlepikov** [comment]
@RitoAgent упражнения конечно надо сделать :)

**Comment by RitoAgent** [comment]
Я сделал. Commit, merge, push сделал. Посмотри у себя - отображается ли файл example2.py ? На всякий случай ссылка вот: https://github.com/KonstantinKlepikov/example-repo/commit/a931a15ae790dd758c7f3eb6f20e74f9dafe3b46

**Comment by KonstantinKlepikov** [comment]
сейчас твоя работа находится ерти где, по всей видимости в ветке dev

1. закомитить изменеения локально
2. отправить в удаленную ветку Dev или любую другую (кроме main)
3. после чего смержить эту ветку с main

не забывай забирать изменеения git fetch и git pull
