### ISSUE TITLE
learn part 4-5 (pages 82-112) - if/else and strings

### ISSUE THREAD

**Issue by KonstantinKlepikov** [KonstantinKlepikov/example-repo#14]
- [x] use one file for examples of code from book. Use all code examples from textual book - in this file or in terminal.
- [ ] use two another files for your solutions of exercises
- [ ] make local branch form this issue (you can create branches from issues remot then local with VSCODE), push local to remote, then merge to main - dont forget for fetch/pull, and link pull-request with this issues (this helps me see what happened on dashboard).

**Comment by RitoAgent** [comment]
а можно поподробнее про 3й пункт make local branch form this issue (you can create branches from issues remot then local with VSCODE), push local to remote, then merge to main - dont forget for fetch/pull, and link pull-request with this issues (this helps me see what happened on dashboard).

**Comment by KonstantinKlepikov** [comment]
@RitoAgent 

- ветку можно создавать прямо из задачи на github - это можно сделать из vscode, я тебе несколько раз показывал как
- к пулркевестам можно линковать задачи, котоыре были сделаны. Это можно сделать при создании пулреквеста в интерфейсе github - я тебе тоже показвл как.

**Comment by RitoAgent** [comment]
use two another files for your solutions of exercises. После того как разобрал все примеры из книги (их довольно много) я делаю упражнения но уже в другом файле. А почему их должно быть 2 а не 1?

**Comment by KonstantinKlepikov** [comment]
@RitoAgent потому что это две разных главы. Они решают две разные функциональные задачи.

**Comment by RitoAgent** [comment]
А интерпретатор можно использовать любой?

**Comment by KonstantinKlepikov** [comment]
@RitoAgent чтор значит "интерпретатор можно"? Твой системный ничем не отличается от виртуального... но ты должен уметь работать с виртуальной средой.

**Comment by RitoAgent** [comment]
У меня invalid syntax практически во всех примерах. В чем подвох?

**Comment by RitoAgent** [comment]
вот кусок кода в самом начале книги (выдает ошибку invalid syntax) : furry = True
large = True
if furry:
    if large:
        print("It's a yeti.")
        else:print("It's a cat!")
else:
if large:
    print("It's a whale!")
    else:print("It's a human. Or a hairless cat.")

**Comment by RitoAgent** [comment]
могу завтра позвонить когда тебе угодно?

**Comment by RitoAgent** [comment]
>>> furry = True
>>> large = True
>>> if furry:
...
if large:
...
print("It's a yeti.")
...
else:
...
print("It's a cat!")
... else:
...
if large:
...
print("It's a whale!")
...
else:
...
print("It's a human. Or a hairless cat.")

**Comment by RitoAgent** [comment]
![Image](https://github.com/KonstantinKlepikov/example-repo/assets/132717651/c4509f8d-2cea-42b0-a7f6-30504e3cac9c)

Тоже неправильно я хз почему

**Comment by RitoAgent** [comment]
всё теперь работает. оказывается нужно нужно следить за отступами поскольку это нужно чтобы понять к какому оператору или циклу относится конструкция(конструкции)

**Comment by KonstantinKlepikov** [comment]
ты можешь писать код сюда в переписку, оборачивая его в маркдаун разметку вот так

```python
this_is_fine = True
```

![image](https://github.com/KonstantinKlepikov/example-repo/assets/20581667/30b61840-4c78-49d5-b7de-e15e57dbfe1d)

**Comment by RitoAgent** [comment]
В-общем упражнения разбиваю на 2 файла формата py. Назову "bool" и "strings". И теперь главный вопрос по 3му пункту - а смысл создавать локальную ветку если я никаких изменений там не делаю? Я же потом новую ветку также переношу в репозиторий и затем делаю пулл реквест с мержем

**Comment by KonstantinKlepikov** [comment]
@RitoAgent не надо bool и striТg - это зарезервирвоанные имена :) Назови по другому.

смысл создавать ветки в том чтобы ты научился работать с гитом

**Comment by RitoAgent** [comment]
У меня вопрос. 5.4. Напишите письмо с использованием нового стиля форматирования. Сохраните
предложенную строку в переменной letter (она понадобится вам в упражнении
ниже):
Dear {salutation} {name},
Thank you for your letter. We are sorry that our {product}
{verbed} in your {room}. Please note that it should never
be used in a {room}, especially near any {animals}.
Send us your receipt and {amount} for shipping and handling.
We will send you another {product} that, in our tests,
is {percent}% less likely to have {verbed}.
Thank you for your support.
Sincerely,
{spokesman}
{job_title}
Как мне это сделать? Я всё перепробовал и мне всегда выдает ошибку invalid syntax

**Comment by RitoAgent** [comment]
Можешь у себя посмотреть? Я pull request сделал

**Comment by KonstantinKlepikov** [comment]
@RitoAgent исправь замечания (замечания смотри в коментариях, котоыре я сотавил к пулреквесту - на дашборде тебе пулреквест должен быть виден)

**Comment by KonstantinKlepikov** [comment]
@RitoAgent кроме того, все комментарии можно увидеть в VSCode


![Image](https://github.com/KonstantinKlepikov/example-repo/assets/20581667/6e1d8631-437f-4a12-b7ad-72786b74358a)
