### ISSUE TITLE
learn part 7 - lists and tuples, pages 119-142

### ISSUE THREAD

**Issue by KonstantinKlepikov** [KonstantinKlepikov/example-repo#17]
- [x] research and try code from part 7, use it in python file
- [ ] solve homework in python file

**Comment by KonstantinKlepikov** [comment]
@RitoAgent это все конечно увлекательно, но где пулревест? :)

**Comment by KonstantinKlepikov** [comment]
@RitoAgent коментарии я добавил

**Comment by RitoAgent** [comment]
Я не знаю как делать последний пример.

**Comment by KonstantinKlepikov** [comment]
@RitoAgent ну так я тебе покажу :)

**Comment by KonstantinKlepikov** [comment]
@RitoAgent я устал смотреть на эту задачу и закрываю ее. Хотя последнее задание ты не осилил.
