### ISSUE TITLE
learn part 10. Classes p.194-223

### ISSUE THREAD

**Issue by KonstantinKlepikov** [KonstantinKlepikov/example-repo#25]

**Comment by RitoAgent** [comment]
Мне нужно еще до 1 июля продлить время. Там 10 заданий. Я пока что сижу на 5 из 10 сижу.

**Comment by KonstantinKlepikov** [comment]
@RitoAgent ну ок

**Comment by RitoAgent** [comment]
у меня 3м задании почему-то выдает ошибку AttributeError: type object 'Thing3' has no attribute 'letters'
в 4м задани тоже что-то не то. Выдает ошибку TypeError: Element() takes no arguments. Скинул код. Можешь посмотреть? В 5м тоже самое что и в 4м задании выдает TypeError: Element() takes no arguments, хотя все аргументы класса у меня заданы (их всего 3) В чем подвох?

**Comment by KonstantinKlepikov** [comment]
@RitoAgent я посмотрю

**Comment by KonstantinKlepikov** [comment]
@RitoAgent тебе надо уяснить простую вещь: классы - это фабрики, которые мы заполняем данными (в атрибутах) и функциями (в виде методов). Когда мы инициализируем класс с помощью круглых скобок - наша фабрика-класс делает копию самой себя. Класс и его копия (инстанс) - это разные объекты. Таким образом мы можем копировать класс множество раз, заполняя его разными данными и используя там, где нам это нужно в коде... при этом не трогая исходник.

**Comment by RitoAgent** [comment]
Мне нужна подсказка по последнему заданию

**Comment by RitoAgent** [comment]
так вот в задании 10.10 я бы хотел узнать а что это за метод does() и как он должен работать? И последняя строка в задании ''Определите
метод does() для класса Robot, который выводит на экран все, что делают его
компоненты."

**Comment by KonstantinKlepikov** [comment]
@RitoAgent когда пишут "определите", то имеют ввиду, что такой метод для данного класса должен написать ты :)

**Comment by KonstantinKlepikov** [comment]
@RitoAgent доделай задачи про классы

**Comment by KonstantinKlepikov** [comment]
@RitoAgent оставил коментарии. Теперь все должно стать понятно.

**Comment by RitoAgent** [comment]
![Image](https://github.com/KonstantinKlepikov/example-repo/assets/132717651/39993f4a-bbeb-4802-8d13-a9c79ab7565f)

Тут оказывается - не сделал пробел для properties и всё - вся конструкция не работает.
