### ISSUE TITLE
learn part 12. Modules p.224-240

### ISSUE THREAD

**Issue by KonstantinKlepikov** [KonstantinKlepikov/example-repo#27]

**Comment by RitoAgent** [comment]
![Image](https://github.com/KonstantinKlepikov/example-repo/assets/132717651/74429d46-d6be-4d8a-8e8d-7be392c3cff9)



![Image](https://github.com/KonstantinKlepikov/example-repo/assets/132717651/d231590c-73fb-455c-b32c-031609387b73)

По модулям вопрос - тут я так понимаю 1 python файл должен вызвать другой python файл да?

**Comment by KonstantinKlepikov** [comment]
@RitoAgent питон-файл - это и есть модуль :)

**Comment by RitoAgent** [comment]
мне нужен перенос на 1 день. Я еще предудыщий не весь разобрал + у меня трудности в этой главе тоже в конце

**Comment by KonstantinKlepikov** [comment]
@RitoAgent так это, спрашивай :)

**Comment by RitoAgent** [comment]
с модулями разобрал.


![Image](https://github.com/KonstantinKlepikov/example-repo/assets/132717651/0490d184-3d6f-47c1-8197-cd7002f30f97)

Вопрос - откуда взяли 2 странных python файла в списке, если я их не добавлял?

**Comment by KonstantinKlepikov** [comment]
@RitoAgent это .pyc файлы - кеш, который интерпретатор использует для того, чтобы не проходить все дерево зависимостей при  каждом запуске файла
