### ISSUE TITLE
clear code of project

### ISSUE THREAD

**Issue by KonstantinKlepikov** [KonstantinKlepikov/example-repo#28]
- install flake8 package from pip to virtual environments of python project
  - activate venv
  - use `pip install flake8` to install flake8 code checker
  - confirm that flake8 is installed by command `pip list`
  - save current list of packages of project in `requirements.txt` by using command `pip freeze>requirements.txt`
- now, as flake8 is installed, пще go to src folder and use `flake8` command from root of project to check code miscalculations and style problems in you project. At this point you must get a list of problems - this list contains in every line: name of python file, string number in a file and problem short text. *Pls fix all style problems in your code* and use this stile condition when you write code later.

Helpful information:

- [flake8 documentation](https://flake8.pycqa.org/en/latest/index.html)
- [PEP 8 – Style Guide for Python Code](https://peps.python.org/pep-0008/)

**Comment by RitoAgent** [comment]
А это для какой задачи?

**Comment by KonstantinKlepikov** [comment]
@RitoAgent это отдельная задача. Прочитай внимательно. Тебе надо установить сторннюю библиоткеу и правести код проекта в нормальный вид с помощью подсказок этой библиотеки.

**Comment by RitoAgent** [comment]
А это для всех проектов нужно сделать ?

**Comment by KonstantinKlepikov** [comment]
@RitoAgent да для всех. Так ты поймешь как писать код правильно. Тут ничего сложного нет - тебе flake8 выводит построчно - в каком файле в какой строке какие нарушения стиля. Исправляешь их и постепенно все становится ок

**Comment by KonstantinKlepikov** [comment]
@RitoAgent на кой черт ты двигаешь эту задачу уже третий раз в выполненное? Ты даже не начал ее делать!!!!

**Comment by RitoAgent** [comment]
я с телефона случайно задел (я ничего не двигал). Хотел почитать комментарии. Еще хотел спросить - а конструкторы в ОПП это потом будет? Я прост на ютубе смотрел по классам и объекты что еще есть конструкторы. А еще я хотел спросить - а почему нельзя было раньше установить это расширение которое ты мне сказал скачать еще в самом начале обучения?

**Comment by KonstantinKlepikov** [comment]
`__init__` - это и есть конструктор класса

@RitoAgent почему нельзя? Потому что тогда бы ты, во-первых, был занят проблемой стиля кода не понимая зачем... а надо было чтобы ты просто поучился структурам. Во-вторых, сейчас ты еще раз пройдешь свою писанину, увидишь свои ошибки и наивность, все повторишь, а заодно исправишь стиль. Это полезно.

**Comment by RitoAgent** [comment]
![Image](https://github.com/KonstantinKlepikov/example-repo/assets/132717651/ec1d045d-c16f-4669-8c1f-5521f597f677)

У меня вот такая вот чудо-ошибка при загрузке на github всплывает

**Comment by RitoAgent** [comment]
![Image](https://github.com/KonstantinKlepikov/example-repo/assets/132717651/35d21d72-7131-4013-af63-ce85d787c469)

И еще вот

**Comment by RitoAgent** [comment]
Всё. Закачал. Забыл .gitignore добавить для ненужных промежуточных файлов

**Comment by KonstantinKlepikov** [comment]
@RitoAgent  кое что осталось не исправленным. Мы не будем сейчас за это цепляться - главное ты понял как улучшать читабельность кода, остальное уже мелочи. Всегда следуй рекомендациям flake8 (как минимум - есть и другие пакеты, помогающие улучшать стиль)


![Image](https://github.com/KonstantinKlepikov/example-repo/assets/20581667/e23f65eb-f85e-4ce2-8153-36a6d5b1fd2b)
