### ISSUE TITLE
kitao/pixel

### ISSUE THREAD

**Issue by RitoAgent** [KonstantinKlepikov/example-repo#34]

**Comment by RitoAgent** [comment]
https://github.com/kitao/pyxel
задача: 
- изучить документацию pyxel (readme на github pixel), 
- создать новый проект игры, 
- развернуть в новом проекте venv с python, 
- установить в вирутальное окружение этого проекта pyxel (смотри инструкцию),
- закомитить репозиторий проекта на github

определи сроки, создай задачу на github project

**Comment by KonstantinKlepikov** [comment]
@RitoAgent хехе, быыло быы прикольно если бы ты этот ижус открыл в репозитории kitao/pixel... вот бы японе о..л бы от такой задачи :)

**Comment by RitoAgent** [comment]
я в gitignore добавлю все файлы кроме своего исходника.

**Comment by RitoAgent** [comment]
Посмотрел все 13 проектов с движком pyxel. Редакторы изображений и звука я потестил. Но у меня есть много вопросов.
