### ISSUE TITLE
read intro and part 2 (pages 55-66) of "introducing to python"

### ISSUE THREAD

**Issue by KonstantinKlepikov** [KonstantinKlepikov/example-repo#5]
- [x] make folder src in project
- [x] add files with examples of code from book, run it and check results
- [x] make homework
- [x] make commit and pull request to main

the book pdf is [here](https://drive.google.com/file/d/1A-frbFf4xLlQ24qr2zJsYL0_bjanBEhF/view?usp=sharing)

**Comment by RitoAgent** [comment]
1) Через какой интерпретатор работают примеры из книги? Я сделал через Python3

**Comment by RitoAgent** [comment]
2. Как выбирать каталог корневой папки?

**Comment by KonstantinKlepikov** [comment]
1. должно работать на python 3.10 в твоей вирутальной среде - python3 - это и есть 3.10 на самом деле в твоем случае
2. `cd <folder-name>` из корневой папки

**Comment by RitoAgent** [comment]
3. make homework - я примеры разобрал через 1 файл example1.py  с использованием терминала. Так вот вопрос - а нужно ли делать отдельный текстовый файл в который можно вывести результаты примеров задач?

**Comment by KonstantinKlepikov** [comment]
@RitoAgent нет, не нужно результаты. Сделай пожалуйста python файл, который можно выполнить и посмотреть что получилось. Этого достаточно.

**Comment by RitoAgent** [comment]
add files with examples of code from book, run it and check results я сделал и всё посмотрел. make homework - что под этим пунктом подразумевается?

**Comment by RitoAgent** [comment]
Я еще добавлю файл Readme.txt чтобы стало понятно что как работает в примерах.

**Comment by KonstantinKlepikov** [comment]
@RitoAgent в конце главы есть пункт "упражнения" - это и есть homework :)

**Comment by RitoAgent** [comment]
На всякий случай предупрежу - я на 2 часа задержу публикацию работы и оставлю в графе review

**Comment by RitoAgent** [comment]
И еще у меня вопрос - почему у меня пропадают все локальные ветки кроме main если перейти ниже по каталогу папки? Я перехожу в папку src и у меня остаётся только main ветка. Серия веток привязана к одной конкретной папке проекта?

**Comment by RitoAgent** [comment]
Сделал commit и pull request. Переношу в review. Завтра буду с утра. У меня еще есть вопросы поскольку я не понимаю механизм работы веток и как правильно делать коммиты и пулл реквесты при этом не перетыкивая все подряд кнопки.
